export let app: HTMLElement;
export let topBar: HTMLElement;
export let chatHeader: HTMLElement;
export let chatMessages: HTMLElement;
export let previewContainer: HTMLElement;
export let promptInput: HTMLTextAreaElement;
export let sendBtn: HTMLElement;
export let promptBuilderBtn: HTMLElement;
export let promptBuilderPanel: HTMLElement;
export let previewFrame: HTMLIFrameElement;
export let codeView: HTMLElement;
export let codeContent: HTMLElement;
export let modalBackdrop: HTMLElement;
export let closeBuilderBtn: HTMLElement;
export let backBtn: HTMLElement;
export let addToPromptBtn: HTMLElement;
export let exportBtn: HTMLElement;
export let durationSlider: HTMLInputElement;
export let delaySlider: HTMLInputElement;
export let durationVal: HTMLElement;
export let delayVal: HTMLElement;
export let inlineModelSelect: HTMLSelectElement;
export let inlineModeSelect: HTMLSelectElement;
export let platformToggle: HTMLElement;

export function initializeElements() {
    app = document.getElementById('app')!;
    topBar = document.getElementById('top-bar')!;
    chatHeader = document.getElementById('chat-header')!;
    chatMessages = document.getElementById('chat-messages')!;
    previewContainer = document.getElementById('preview-container')!;
    promptInput = document.getElementById('prompt-input') as HTMLTextAreaElement;
    sendBtn = document.getElementById('send-btn')!;
    promptBuilderBtn = document.getElementById('prompt-builder-btn')!;
    promptBuilderPanel = document.getElementById('prompt-builder-panel')!;
    previewFrame = document.getElementById('preview-frame') as HTMLIFrameElement;
    codeView = document.getElementById('code-view')!;
    codeContent = document.getElementById('code-content')!;
    modalBackdrop = document.getElementById('modal-backdrop')!;
    closeBuilderBtn = document.getElementById('close-builder-btn')!;
    backBtn = document.getElementById('back-btn')!;
    addToPromptBtn = document.getElementById('add-to-prompt-btn')!;
    exportBtn = document.getElementById('export-btn')!;
    durationSlider = document.getElementById('builder-anim-duration') as HTMLInputElement;
    delaySlider = document.getElementById('builder-anim-delay') as HTMLInputElement;
    durationVal = document.getElementById('val-anim-duration')!;
    delayVal = document.getElementById('val-anim-delay')!;
    inlineModelSelect = document.getElementById('inline-model-select') as HTMLSelectElement;
    inlineModeSelect = document.getElementById('inline-mode-select') as HTMLSelectElement;
    platformToggle = document.getElementById('platform-toggle')!;
}
